# Derive one observed translation unit; never modify the pinned checkout.
set(_original "${YMIR_SOURCE_DIR}/libs/ymir-core/src/ymir/hw/vdp/vdp.cpp")
file(SHA256 "${_original}" _sha)
if(NOT _sha STREQUAL "ab9cfce4c31f81e80874579779d8eefa976113a34a159036600fc4d9118e1202")
  message(FATAL_ERROR "Unsupported upstream vdp.cpp; instrumentation anchors are pinned")
endif()
file(READ "${_original}" _code)
function(observe_replace_once before after)
  string(FIND "${_code}" "${before}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "Missing observation anchor: ${before}")
  endif()
  string(LENGTH "${before}" _len)
  math(EXPR _end "${_pos}+${_len}")
  string(SUBSTRING "${_code}" ${_end} -1 _rest)
  string(FIND "${_rest}" "${before}" _duplicate)
  if(NOT _duplicate EQUAL -1)
    message(FATAL_ERROR "Ambiguous observation anchor: ${before}")
  endif()
  string(REPLACE "${before}" "${after}" _code "${_code}")
  set(_code "${_code}" PARENT_SCOPE)
endfunction()
observe_replace_once("#include <ymir/hw/vdp/vdp.hpp>" "#include <ymir/hw/vdp/vdp.hpp>\n#include \"observer_bridge.hpp\"")
observe_replace_once("    , m_scheduler(scheduler) {" "    , m_scheduler(scheduler) {\n    AOCharacterBind(m_scheduler, m_state);")
observe_replace_once("    m_state.displayFB ^= 1;" "    m_state.displayFB ^= 1;\n    AOCharacterObserve(\"vdp1_swap_after_flip\", m_scheduler, m_state, m_VDP1CtlState.drawing);")
observe_replace_once("        m_VDP1CtlState.drawing = true;" "        m_VDP1CtlState.drawing = true;\n        AOCharacterObserve(\"vdp1_begin\", m_scheduler, m_state, m_VDP1CtlState.drawing);")
observe_replace_once("    m_renderer->VDP1EndFrame();" "    AOCharacterObserve(\"vdp1_end\", m_scheduler, m_state, m_VDP1CtlState.drawing);\n    m_renderer->VDP1EndFrame();")
observe_replace_once("                m_VDP1CtlState.drawing = false;" "                m_VDP1CtlState.drawing = false;\n                AOCharacterObserve(\"vdp1_end_requested\", m_scheduler, m_state, m_VDP1CtlState.drawing);")
observe_replace_once("        m_renderer->VDP2RenderLine(m_state.regs2.VCNT);" "        AOCharacterObserve(\"vdp2_render_line\", m_scheduler, m_state, m_VDP1CtlState.drawing, m_state.regs2.VCNT);\n        m_renderer->VDP2RenderLine(m_state.regs2.VCNT);")
observe_replace_once("    m_state.regs1.currCommandAddress = cmdAddress;" "    m_state.regs1.currCommandAddress = cmdAddress;\n    AOCharacterObserve(\"command_fetch\", m_scheduler, m_state, m_VDP1CtlState.drawing, cmdAddress);")
observe_replace_once("        m_renderer->VDP1ExecuteCommand(cmdAddress, control);" "        AOCharacterObserve(\"command_execute_before\", m_scheduler, m_state, m_VDP1CtlState.drawing, cmdAddress);\n        m_renderer->VDP1ExecuteCommand(cmdAddress, control);\n        AOCharacterObserve(\"command_execute_after\", m_scheduler, m_state, m_VDP1CtlState.drawing, cmdAddress);")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
set(_observed "${CMAKE_CURRENT_BINARY_DIR}/generated/vdp_character.cpp")
file(WRITE "${_observed}" "${_code}")
get_target_property(_sources ymir-core SOURCES)
set(_replacement_count 0)
set(_observed_sources "")
foreach(_item IN LISTS _sources)
  if(_item MATCHES "(^|/)src/ymir/hw/vdp/vdp\\.cpp$")
    list(APPEND _observed_sources "${_observed}")
    math(EXPR _replacement_count "${_replacement_count}+1")
  else()
    list(APPEND _observed_sources "${_item}")
  endif()
endforeach()
if(NOT _replacement_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one VDP translation unit")
endif()
set_property(TARGET ymir-core PROPERTY SOURCES "${_observed_sources}")
target_include_directories(ymir-core PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
